
ingress:
  hostname: colorization.dyn.cloud.e-infra.cz
  backendPath: /api(/.*)?

global:
  backendPort: 8000



replicaCount: 1
image:
  repository: cerit.io/vojtama/cgan-backend
  tag: "0.1"
service:
  port: 8000
  targetPort: 8000

selectorLabels:
  app: backend