# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}-ingress
#   labels:
#     app.kubernetes.io/name: {{ .Chart.Name }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#     kubernetes.io/tls-acme: "true"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
# spec:
#   ingressClassName: nginx
#   tls:
#     - hosts:
#         - {{ .Values.ingress.hostname | quote}}
#       secretName: {{ .Values.ingress.hostname}}-tls
#   rules:
#     - host: {{ .Values.ingress.hostname | quote }}
#       http:
#         paths:
#           # Route API calls to the backend service
#           - path: /api(/|$)(.*)
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: {{ .Release.Name }}-colorization-backend # Service from the backend subchart
#                 port:
#                   number: {{ (index .Values "colorization-backend").service.port }}

#           # Route everything else to the frontend service
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ .Release.Name }}-colorization-frontend # Service from the frontend subchart
#                 port:
#                   number: {{ (index .Values "colorization-frontend").service.port }}