apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - name: frontend-port
    port: {{ .Values.service.port | default 80 }}
    targetPort: {{ .Values.service.targetPort | default 3000 }}
  selector:
    {{- toYaml .Values.selectorLabels | nindent 4 }}

